services:
  backend:
    build:
      context: ./backend
    container_name: clima-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/climaapp
      - JWT_SECRET=secreto-superseguro
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: clima-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
